order-query:
  internal:
    datasource:
      mysql:
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/orderquery
        driver-class-name: com.mysql.cj.jdbc.Driver